# Generated by Django 3.2.5 on 2021-07-15 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tube', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCommentReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=500, verbose_name='リプライ')),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tube.videocomment', verbose_name='リプライ対象のコメント')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
            options={
                'db_table': 'comment_reply',
            },
        ),
    ]
