# Generated by Django 3.2.5 on 2021-07-15 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0004_videocommentreplytoreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocommentreplytoreply',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tube.videocommentreply', verbose_name='リプライ対象のコメント'),
        ),
    ]
